import { useCallback, useEffect, useState } from 'react'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import CircularProgress from '@mui/material/CircularProgress'
import Dialog from '@mui/material/Dialog'
import DialogActions from '@mui/material/DialogActions'
import DialogContent from '@mui/material/DialogContent'
import DialogTitle from '@mui/material/DialogTitle'
import Divider from '@mui/material/Divider'
import Typography from '@mui/material/Typography'
import useMediaQuery from '@mui/material/useMediaQuery'
import { useTheme } from '@mui/material/styles'
import apiClient from '../../api/client'
import { formatDateTime } from '../../utils/formatDate'
import ErrorAlert from '../layout/ErrorAlert'
import JobStatusChip from '../common/JobStatusChip'
import type { LetterJobDetail } from '../../types'

interface Props {
  jobId: string | null
  onClose: () => void
}

function FieldRows({ rows }: { rows: { label: string; value: string }[] }) {
  return (
    <Box>
      {rows.map((row, i) => (
        <Box
          key={`${row.label}-${i}`}
          display="flex"
          justifyContent="space-between"
          gap={2}
          py={0.75}
        >
          <Typography variant="body2" color="text.secondary" sx={{ flexShrink: 0 }}>
            {row.label}
          </Typography>
          <Typography variant="body2" sx={{ textAlign: 'right', wordBreak: 'break-word' }}>
            {row.value}
          </Typography>
        </Box>
      ))}
    </Box>
  )
}

export default function LetterDetailDialog({ jobId, onClose }: Props) {
  const theme = useTheme()
  const fullScreen = useMediaQuery(theme.breakpoints.down('sm'))
  const [detail, setDetail] = useState<LetterJobDetail | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchDetail = useCallback(async (id: string) => {
    setLoading(true)
    setError(null)
    setDetail(null)
    try {
      const { data } = await apiClient.get<LetterJobDetail>(`/api/letters/${id}/details`)
      setDetail(data)
    } catch {
      setError('Failed to load letter details.')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    if (jobId) fetchDetail(jobId)
  }, [jobId, fetchDetail])

  return (
    <Dialog open={jobId !== null} onClose={onClose} fullScreen={fullScreen} maxWidth="sm" fullWidth>
      <DialogTitle>Letter details</DialogTitle>
      <DialogContent dividers>
        {error && <ErrorAlert message={error} onClose={() => setError(null)} />}

        {loading ? (
          <Box display="flex" justifyContent="center" py={6}>
            <CircularProgress size={28} />
          </Box>
        ) : detail ? (
          <Box display="flex" flexDirection="column" gap={2}>
            <Box>
              <Box display="flex" justifyContent="space-between" alignItems="center" gap={2}>
                <Typography variant="h6">{detail.template_name}</Typography>
                <JobStatusChip status={detail.status} />
              </Box>
              <Typography variant="body2" color="text.secondary">
                {detail.association_name}
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Generated by {detail.created_by_name} · {formatDateTime(detail.created_at)}
              </Typography>
            </Box>

            <Box>
              <Typography variant="subtitle2" gutterBottom>
                Your entries
              </Typography>
              <Divider sx={{ mb: 1 }} />
              {detail.entries.length > 0 ? (
                <FieldRows rows={detail.entries} />
              ) : (
                <Typography variant="body2" color="text.secondary">
                  No entries recorded.
                </Typography>
              )}
            </Box>

            {detail.derived.length > 0 && (
              <Box>
                <Typography variant="subtitle2" gutterBottom>
                  Resolved details
                </Typography>
                <Divider sx={{ mb: 1 }} />
                <FieldRows rows={detail.derived} />
              </Box>
            )}
          </Box>
        ) : null}
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose}>Close</Button>
      </DialogActions>
    </Dialog>
  )
}
