"""enforce one manager per association

Revision ID: 738717eb183f
Revises: e00d3eed4c2a
Create Date: 2026-04-03 23:57:41.956146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738717eb183f'
down_revision: Union[str, Sequence[str], None] = 'e00d3eed4c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_associations', ['association_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_associations', type_='unique')
    # ### end Alembic commands ###
