"""add password_change_required to users

Revision ID: f2a1db2a2c8d
Revises: 2c22474b9876
Create Date: 2026-04-22 16:48:23.400891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a1db2a2c8d'
down_revision: Union[str, Sequence[str], None] = '2c22474b9876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'password_change_required',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('true'),
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_change_required')
    # ### end Alembic commands ###
